name: Release Open source Marqo artefacts.

on:
  push:
    tags:
      - v*

jobs:
  docker-release:
    name: Build and push Docker images for `marqoai/marqo`
    runs-on: ubuntu-latest
  
    steps:     
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU # https://github.com/docker/setup-qemu-action
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build `marqoai/marqo`
        run: |
          DOCKER_BUILDKIT=1 
          docker buildx build --platform linux/arm64,linux/amd64 --push . -t marqoai/marqo:test-${{ github.ref_name }}

      - name: Push `marqoai/marqo` to DockerHub
        run: docker push $marqoai/marqo:test-${{ github.ref_name }}